<?php
declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

return [
    // `config` ergänzt die kanonische `customization`-Definition aus `theme.json`
    // nur noch um Legacy-/UI-Felder, die dort bisher nicht beschrieben sind.
    'config' => [
        'colors' => [
            'title' => '🎨 Farben',
            'sections' => [
                'primary_color'        => ['label' => 'Primärfarbe',              'type' => 'color',  'default' => '#1e3a5f'],
                'primary_dark'         => ['label' => 'Primär Dunkel',            'type' => 'color',  'default' => '#0f2340'],
                'primary_mid'          => ['label' => 'Primär Mitte',             'type' => 'color',  'default' => '#1a3255'],
                'primary_light'        => ['label' => 'Primär Hell',              'type' => 'color',  'default' => '#2a4f7c'],
                'accent_color'         => ['label' => 'Akzent (Gold)',            'type' => 'color',  'default' => '#e8a838'],
                'accent_hover'         => ['label' => 'Akzent Hover',             'type' => 'color',  'default' => '#d4922a'],
                'accent_blue'          => ['label' => 'Akzent Blau',              'type' => 'color',  'default' => '#4a9eff'],
                'accent_blue2'         => ['label' => 'Akzent Blau 2',            'type' => 'color',  'default' => '#2d7dd2'],
                'accent_teal'          => ['label' => 'Akzent Teal',              'type' => 'color',  'default' => '#0d9488'],
                'accent_teal_light'    => ['label' => 'Akzent Teal Hell',         'type' => 'color',  'default' => '#14b8a6'],
                'bg_header1'           => ['label' => 'Header-BG 1',              'type' => 'color',  'default' => '#111827'],
                'bg_header2'           => ['label' => 'Header-BG 2',              'type' => 'color',  'default' => '#162030'],
                'bg_header3'           => ['label' => 'Header-BG 3',              'type' => 'color',  'default' => '#0e1a28'],
                'bg_primary'           => ['label' => 'Seite BG',                 'type' => 'color',  'default' => '#ffffff'],
                'bg_secondary'         => ['label' => 'Seite BG sekundär',        'type' => 'color',  'default' => '#f1f5f9'],
                'bg_dark'              => ['label' => 'Dark-Mode BG',             'type' => 'color',  'default' => '#0a0f1a'],
                'text_primary'         => ['label' => 'Text Primär',              'type' => 'color',  'default' => '#1e293b'],
                'text_secondary'       => ['label' => 'Text Sekundär',            'type' => 'color',  'default' => '#4a5568'],
                'text_muted'           => ['label' => 'Text Gedimmt',             'type' => 'color',  'default' => '#7a8898'],
                'text_nav'             => ['label' => 'Nav Text (allgemein)',     'type' => 'color',  'default' => '#e2e8f0'],
                'text_nav_member'      => ['label' => 'Member-Bar Text',          'type' => 'color',  'default' => '#e2e8f0'],
                'text_nav_main'        => ['label' => 'Hauptnav Text',            'type' => 'color',  'default' => '#e2e8f0'],
                'text_nav_quicklinks'  => ['label' => 'Quicklinks Text',          'type' => 'color',  'default' => '#b0bec5'],
                'text_nav_dropdown'    => ['label' => 'Dropdown Text',            'type' => 'color',  'default' => '#e2e8f0'],
                'page_edge_tint_color' => ['label' => 'Seitenrand-Tönung',        'type' => 'color',  'default' => '#0f172a'],
                'logo_suffix_color'    => ['label' => 'Logo-Suffix Farbe',        'type' => 'color',  'default' => '#e8a838'],
                'border_light'         => ['label' => 'Rahmenfarbe',              'type' => 'color',  'default' => '#dde3ea'],
                'footer_bg'            => ['label' => 'Footer BG',                'type' => 'color',  'default' => '#0d1828'],
                'footer_bottom_bg'     => ['label' => 'Footer Bottom BG',         'type' => 'color',  'default' => '#080d15'],
                'footer_border'        => ['label' => 'Footer Border',            'type' => 'color',  'default' => '#2d7dd2'],
                'success_color'        => ['label' => 'Status: Erfolg',           'type' => 'color',  'default' => '#16a34a'],
                'error_color'          => ['label' => 'Status: Fehler',           'type' => 'color',  'default' => '#dc2626'],
                'progress_bar_start'   => ['label' => 'Progress-Bar Start',       'type' => 'color',  'default' => '#2d7dd2'],
                'progress_bar_end'     => ['label' => 'Progress-Bar Ende',        'type' => 'color',  'default' => '#e8a838'],
            ],
        ],
        'typography' => [
            'title' => '🔤 Typografie',
            'sections' => [
                'font_family_ui'           => ['label' => 'UI-Schrift',               'type' => 'select', 'default' => 'barlow',          'options' => ['barlow' => 'Barlow', 'system' => 'System', 'inter' => 'Inter', 'roboto' => 'Roboto', 'open-sans' => 'Open Sans', 'lato' => 'Lato', 'montserrat' => 'Montserrat', 'poppins' => 'Poppins', 'source-sans' => 'Source Sans', 'nunito' => 'Nunito']],
                'font_family_brand'        => ['label' => 'Brand-Schrift',            'type' => 'select', 'default' => 'barlow-condensed', 'options' => ['barlow-condensed' => 'Barlow Condensed', 'barlow' => 'Barlow', 'system' => 'System', 'roboto-condensed' => 'Roboto Condensed', 'oswald' => 'Oswald', 'montserrat' => 'Montserrat', 'rajdhani' => 'Rajdhani', 'exo2' => 'Exo 2']],
                'font_family_code'         => ['label' => 'Code-Schrift',             'type' => 'select', 'default' => 'jetbrains-mono',   'options' => ['jetbrains-mono' => 'JetBrains Mono', 'fira-code' => 'Fira Code', 'source-code' => 'Source Code Pro', 'cascadia' => 'Cascadia Code', 'system-mono' => 'System Mono']],
                'font_size_base'           => ['label' => 'Basis-Schriftgröße (px)',  'type' => 'number', 'default' => '14.5'],
                'font_size_post'           => ['label' => 'Artikel-Schriftgröße (px)','type' => 'number', 'default' => '15.5'],
                'line_height_base'         => ['label' => 'Zeilenhöhe (UI)',          'type' => 'number', 'default' => '1.55'],
                'line_height_post'         => ['label' => 'Zeilenhöhe (Post)',        'type' => 'number', 'default' => '1.8'],
                'font_weight_heading'      => ['label' => 'Überschriften-Gewicht',    'type' => 'select', 'default' => '700',              'options' => ['400' => '400 (Normal)', '500' => '500', '600' => '600 (Semibold)', '700' => '700 (Bold)', '800' => '800', '900' => '900 (Black)']],
                'font_weight_nav'          => ['label' => 'Navigation-Gewicht',       'type' => 'select', 'default' => '600',              'options' => ['400' => '400 (Normal)', '500' => '500', '600' => '600 (Semibold)', '700' => '700 (Bold)', '800' => '800']],
                'article_title_fontsize'   => ['label' => 'Artikel-Karte: Titel (px)','type' => 'number', 'default' => '16'],
                'tile_title_fontsize'      => ['label' => 'Kachel: Titel (px)',       'type' => 'number', 'default' => '15'],
                'article_excerpt_fontsize' => ['label' => 'Artikel: Auszug (px)',     'type' => 'number', 'default' => '13'],
                'article_excerpt_length'   => ['label' => 'Artikel: Auszug-Länge',    'type' => 'number', 'default' => '180'],
                'tile_excerpt_fontsize'    => ['label' => 'Kachel: Auszug (px)',      'type' => 'number', 'default' => '12'],
                'tile_excerpt_length'      => ['label' => 'Kachel: Auszug-Länge',     'type' => 'number', 'default' => '160'],
            ],
        ],
        'layout' => [
            'title' => '📐 Layout',
            'sections' => [
                'container_width'          => ['label' => 'Container-Breite (px)',       'type' => 'number',   'default' => '1060'],
                'page_edge_tint_opacity'   => ['label' => 'Seitenrand-Tönung Deckkraft', 'type' => 'number',   'default' => '0.12', 'min' => 0, 'max' => 0.3, 'step' => 0.01],
                'sidebar_width'            => ['label' => 'Sidebar-Breite (px)',         'type' => 'number',   'default' => '280'],
                'border_radius'            => ['label' => 'Rahmen-Radius klein (px)',    'type' => 'number',   'default' => '4'],
                'border_radius_md'         => ['label' => 'Rahmen-Radius mittel (px)',   'type' => 'number',   'default' => '6'],
                'content_gap'              => ['label' => 'Content-Lücke (px)',          'type' => 'number',   'default' => '28'],
                'spacing_header_content'   => ['label' => 'Abstand Header→Content (px)', 'type' => 'number',   'default' => '25'],
                'spacing_content_footer'   => ['label' => 'Abstand Content→Footer (px)', 'type' => 'number',   'default' => '25'],
                'spacing_sections'         => ['label' => 'Abstand zwischen Sektionen',  'type' => 'number',   'default' => '40'],
                'show_breadcrumb'          => ['label' => 'Breadcrumb anzeigen',         'type' => 'checkbox', 'default' => true],
                'breadcrumb_on_posts'      => ['label' => 'Breadcrumb auf Posts',        'type' => 'checkbox', 'default' => true],
                'breadcrumb_on_pages'      => ['label' => 'Breadcrumb auf Seiten',       'type' => 'checkbox', 'default' => true],
                'sidebar_position'         => ['label' => 'Sidebar-Position',            'type' => 'select',   'default' => 'right', 'options' => ['right' => 'Rechts', 'left' => 'Links', 'none' => 'Keine Sidebar']],
                'enable_sticky_header'     => ['label' => 'Sticky Header',               'type' => 'checkbox', 'default' => true],
                'enable_progress_bar'      => ['label' => 'Lese-Progress-Bar',           'type' => 'checkbox', 'default' => true],
                'enable_back_to_top'       => ['label' => 'Back-to-Top Button',          'type' => 'checkbox', 'default' => true],
                'enable_dark_mode_toggle'  => ['label' => 'Dark Mode Toggle',            'type' => 'checkbox', 'default' => true],
                'enable_scroll_animations' => ['label' => 'Scroll-Animationen',          'type' => 'checkbox', 'default' => true],
            ],
        ],
        'header' => [
            'title' => '🖥️ Header',
            'sections' => [
                'logo_text_part1'           => ['label' => 'Logo Teil 1',             'type' => 'text',     'default' => '365'],
                'logo_text_part2'           => ['label' => 'Logo Teil 2',             'type' => 'text',     'default' => 'CMS'],
                'logo_text_suffix'          => ['label' => 'Logo Suffix',             'type' => 'text',     'default' => '.DE'],
                'logo_url'                  => ['label' => 'Logo Bild-URL',           'type' => 'text',     'default' => ''],
                'show_logo_text_with_image' => ['label' => 'Logo-Text + Bild zusammen', 'type' => 'checkbox', 'default' => false],
                'logo_max_height'           => ['label' => 'Logo Höhe (px)',          'type' => 'number',   'default' => '28'],
                'logo_accent_color'         => ['label' => 'Logo-Akzentfarbe',        'type' => 'color',    'default' => '#4a9eff'],
                'show_member_bar'           => ['label' => 'Member-Bar anzeigen',     'type' => 'checkbox', 'default' => true],
                'member_bar_height'         => ['label' => 'Member-Bar Höhe (px)',    'type' => 'number',   'default' => '36'],
                'main_nav_height'           => ['label' => 'Hauptnav Höhe (px)',      'type' => 'number',   'default' => '48'],
                'show_search_bar'           => ['label' => 'Suchleiste anzeigen',     'type' => 'checkbox', 'default' => true],
                'search_placeholder'        => ['label' => 'Suche Platzhalter',       'type' => 'text',     'default' => 'Suchen…'],
                'show_rss_link'             => ['label' => 'RSS-Link anzeigen',       'type' => 'checkbox', 'default' => true],
                'show_quicklinks'           => ['label' => 'Quicklinks-Bar anzeigen', 'type' => 'checkbox', 'default' => true],
                'sub_bar_height'            => ['label' => 'Quicklinks-Bar Höhe (px)','type' => 'number',   'default' => '30'],
            ],
        ],
        'footer' => [
            'title' => '🔻 Footer',
            'sections' => [
                'footer_brand_name'       => ['label' => 'Footer Brand Name',      'type' => 'text',     'default' => 'phinit.de'],
                'footer_tagline'          => ['label' => 'Footer Tagline',         'type' => 'text',     'default' => 'IT-Profi · M365 · Scripting · Open Source'],
                'footer_col2_title'       => ['label' => 'Spalte 2 Titel',         'type' => 'text',     'default' => 'Themen'],
                'footer_col3_title'       => ['label' => 'Spalte 3 Titel',         'type' => 'text',     'default' => 'Seiten'],
                'footer_col4_title'       => ['label' => 'Spalte 4 Titel',         'type' => 'text',     'default' => 'Kontakt'],
                'copyright_text'          => ['label' => 'Copyright-Text',         'type' => 'text',     'default' => '© {year} phinit.de'],
                'show_footer_social'      => ['label' => 'Social-Links im Footer', 'type' => 'checkbox', 'default' => true],
                'show_consent_banner'     => ['label' => 'Consent-Banner anzeigen','type' => 'checkbox', 'default' => true],
                'consent_text'            => ['label' => 'Consent Banner Text',    'type' => 'textarea', 'default' => 'Diese Website verwendet Cookies für Analysezwecke.'],
                'consent_privacy_url'     => ['label' => 'Datenschutz-URL',        'type' => 'text',     'default' => '/cookie-policy'],
                'show_network_bar'        => ['label' => 'Network/Partner-Bar',    'type' => 'checkbox', 'default' => false],
                'network_bar_link1_label' => ['label' => 'Network-Link 1 Label',   'type' => 'text',     'default' => 'phinit.de'],
                'network_bar_link1_url'   => ['label' => 'Network-Link 1 URL',     'type' => 'text',     'default' => 'https://phinit.de'],
                'network_bar_link2_label' => ['label' => 'Network-Link 2 Label',   'type' => 'text',     'default' => 'phscripts.de'],
                'network_bar_link2_url'   => ['label' => 'Network-Link 2 URL',     'type' => 'text',     'default' => 'https://phscripts.de'],
                'network_bar_link3_label' => ['label' => 'Network-Link 3 Label',   'type' => 'text',     'default' => '365network.de'],
                'network_bar_link3_url'   => ['label' => 'Network-Link 3 URL',     'type' => 'text',     'default' => 'https://365network.de'],
                'network_bar_link4_label' => ['label' => 'Network-Link 4 Label (leer = aus)', 'type' => 'text', 'default' => 'ms365insights.de'],
                'network_bar_link4_url'   => ['label' => 'Network-Link 4 URL',     'type' => 'text',     'default' => 'https://ms365insights.de'],
                'network_bar_link5_label' => ['label' => 'Network-Link 5 Label (leer = aus)', 'type' => 'text', 'default' => ''],
                'network_bar_link5_url'   => ['label' => 'Network-Link 5 URL',     'type' => 'text',     'default' => ''],
            ],
        ],
        'homepage' => [
            'title' => '🏠 Startseite',
            'sections' => [
                'show_repo_card'             => ['label' => 'Repo-Card anzeigen',           'type' => 'checkbox', 'default' => true],
                'repo_card_title'            => ['label' => 'Repo-Card Titel',              'type' => 'text',     'default' => 'PS-easyIT Script-Repository'],
                'repo_card_description'      => ['label' => 'Repo-Card Beschreibung',       'type' => 'textarea', 'default' => '25+ Code-signierte PowerShell-Module für M365 Administration. Enterprise-ready & Open Source.'],
                'repo_card_badge'            => ['label' => 'Repo-Card Badge',              'type' => 'text',     'default' => '25+ Repos'],
                'repo_card_btn_text'         => ['label' => 'Repo-Card Button Text',        'type' => 'text',     'default' => 'Zum GitHub →'],
                'repo_card_btn_url'          => ['label' => 'Repo-Card Button URL',         'type' => 'text',     'default' => 'https://github.com/phinit/'],
                'show_article_list'          => ['label' => 'Artikel-Liste anzeigen',       'type' => 'checkbox', 'default' => true],
                'article_list_label'         => ['label' => 'Sektion-Label',                'type' => 'text',     'default' => 'Aktuell'],
                'article_list_count'         => ['label' => 'Anzahl Artikel',               'type' => 'number',   'default' => '4'],
                'article_list_link_url'      => ['label' => '„Alle Beiträge" URL',         'type' => 'text',     'default' => '/blog'],
                'article_thumb_width'        => ['label' => 'Thumbnail Breite (px)',        'type' => 'number',   'default' => '190'],
                'article_thumb_height'       => ['label' => 'Thumbnail Höhe (px)',          'type' => 'number',   'default' => '115'],
                'show_article_excerpt'       => ['label' => 'Auszug anzeigen',              'type' => 'checkbox', 'default' => true],
                'show_article_meta'          => ['label' => 'Meta (Kat/Datum/Lesezeit)',    'type' => 'checkbox', 'default' => true],
                'show_article_badge'         => ['label' => 'Kategorie-Badge auf Thumb',    'type' => 'checkbox', 'default' => true],
                'show_meta_category'         => ['label' => 'Meta: Kategorie',              'type' => 'checkbox', 'default' => true],
                'show_meta_date'             => ['label' => 'Meta: Datum',                  'type' => 'checkbox', 'default' => true],
                'show_meta_readtime'         => ['label' => 'Meta: Lesezeit',               'type' => 'checkbox', 'default' => true],
                'show_list_sidebar'          => ['label' => 'Sidebar neben „Aktuell"',     'type' => 'checkbox', 'default' => false],
                'list_sidebar_width'         => ['label' => 'Sidebar Breite (px)',          'type' => 'number',   'default' => '260'],
                'list_sidebar_title'         => ['label' => 'Sidebar Titel',                'type' => 'text',     'default' => ''],
                'list_sidebar_content'       => ['label' => 'Sidebar Inhalt (HTML)',        'type' => 'textarea', 'default' => ''],
                'sidebar_show_identity'      => ['label' => 'Widget: Site-Identity',        'type' => 'checkbox', 'default' => true],
                'sidebar_identity_logo_url'  => ['label' => 'Identity Logo-URL',            'type' => 'text',     'default' => ''],
                'sidebar_identity_tagline'   => ['label' => 'Identity Tagline',             'type' => 'text',     'default' => ''],
                'sidebar_identity_link_url'  => ['label' => 'Identity Link',                'type' => 'text',     'default' => '/'],
                'sidebar_show_projects'      => ['label' => 'Widget: Projekt-Hinweise',     'type' => 'checkbox', 'default' => true],
                'sidebar_project1_name'      => ['label' => 'Projekt 1 Name',               'type' => 'text',     'default' => '365CMS.DE'],
                'sidebar_project1_logo_url'  => ['label' => 'Projekt 1 Logo-URL',           'type' => 'text',     'default' => ''],
                'sidebar_project1_desc'      => ['label' => 'Projekt 1 Beschreibung',       'type' => 'text',     'default' => 'Das eigene CMS – modular & flexibel'],
                'sidebar_project1_url'       => ['label' => 'Projekt 1 URL',                'type' => 'text',     'default' => 'https://365cms.de'],
                'sidebar_project2_name'      => ['label' => 'Projekt 2 Name',               'type' => 'text',     'default' => '365NETWORK.DE'],
                'sidebar_project2_logo_url'  => ['label' => 'Projekt 2 Logo-URL',           'type' => 'text',     'default' => ''],
                'sidebar_project2_desc'      => ['label' => 'Projekt 2 Beschreibung',       'type' => 'text',     'default' => 'Business-Netzwerk-Plattform'],
                'sidebar_project2_url'       => ['label' => 'Projekt 2 URL',                'type' => 'text',     'default' => 'https://365network.de'],
                'sidebar_show_status'        => ['label' => 'Widget: Dienst-Status',        'type' => 'checkbox', 'default' => true],
                'sidebar_status_label'       => ['label' => 'Status Label',                 'type' => 'text',     'default' => 'Dienst-Status'],
                'sidebar_status_services'    => ['label' => 'Status-Dienste (Name|URL|Kürzel)', 'type' => 'textarea', 'default' => "Microsoft 365|https://status.office365.com|M365\nAzure|https://status.azure.com|AZ\nGitHub|https://githubstatus.com|GH\nCloudflare|https://www.cloudflarestatus.com|CF"],
                'sidebar_show_downloads'     => ['label' => 'Widget: Downloads',            'type' => 'checkbox', 'default' => false],
                'sidebar_downloads_label'    => ['label' => 'Downloads Label',              'type' => 'text',     'default' => 'Downloads & Checklisten'],
                'sidebar_downloads_items'    => ['label' => 'Download-Links (Bezeichnung|URL)', 'type' => 'textarea', 'default' => ''],
                'sidebar_show_social'        => ['label' => 'Widget: Social-Links',         'type' => 'checkbox', 'default' => true],
                'sidebar_social_label'       => ['label' => 'Social Label',                 'type' => 'text',     'default' => 'Folge uns'],
                'sidebar_show_notice'        => ['label' => 'Widget: Hinweis/Ankündigung',  'type' => 'checkbox', 'default' => false],
                'sidebar_notice_title'       => ['label' => 'Hinweis Titel',                'type' => 'text',     'default' => '💡 Aktueller Hinweis'],
                'sidebar_notice_text'        => ['label' => 'Hinweis Text',                 'type' => 'textarea', 'default' => ''],
                'sidebar_notice_url'         => ['label' => 'Hinweis Link URL',             'type' => 'text',     'default' => ''],
                'sidebar_notice_url_text'    => ['label' => 'Hinweis Link Text',            'type' => 'text',     'default' => 'Mehr erfahren →'],
                'sidebar_show_featured_posts'=> ['label' => 'Widget: Empfohlene Artikel',   'type' => 'checkbox', 'default' => false],
                'sidebar_featured_posts_label' => ['label' => 'Empfohlene Artikel Label',   'type' => 'text',     'default' => '📌 Empfohlene Artikel'],
                'sidebar_featured_badge_style' => ['label' => 'Featured Badge-Stil',        'type' => 'select',   'default' => 'teal', 'options' => ['neutral' => 'Neutral', 'teal' => 'Teal', 'gold' => 'Gold', 'dark' => 'Dark']],
                'sidebar_featured_rotate_seconds' => ['label' => 'Featured Wechselintervall (Sekunden)', 'type' => 'number', 'default' => '6', 'min' => 2, 'max' => 60],
                'sidebar_featured_title_size' => ['label' => 'Featured Titelgröße (px)',   'type' => 'number',   'default' => '12.5', 'min' => 10, 'max' => 20],
                'sidebar_featured_badge_size' => ['label' => 'Featured Badge-Schriftgröße (px)', 'type' => 'number', 'default' => '10', 'min' => 8, 'max' => 18],
                'sidebar_featured_image_layout' => ['label' => 'Eigene Featured-Bilder: Position', 'type' => 'select', 'default' => 'auto', 'options' => ['auto' => 'Automatisch (kompakt bei Projekten/Social)', 'side' => 'Daneben', 'below' => 'Darunter']],
                'sidebar_featured_post_1'    => ['label' => 'Empfohlener Beitrag 1',        'type' => 'post_picker', 'default' => ''],
                'sidebar_featured_post_2'    => ['label' => 'Empfohlener Beitrag 2',        'type' => 'post_picker', 'default' => ''],
                'sidebar_featured_post_3'    => ['label' => 'Empfohlener Beitrag 3',        'type' => 'post_picker', 'default' => ''],
                'sidebar_featured_post_4'    => ['label' => 'Empfohlener Beitrag 4',        'type' => 'post_picker', 'default' => ''],
                'sidebar_featured_post_5'    => ['label' => 'Empfohlener Beitrag 5',        'type' => 'post_picker', 'default' => ''],
                'sidebar_featured_post_6'    => ['label' => 'Empfohlener Beitrag 6',        'type' => 'post_picker', 'default' => ''],
                'sidebar_featured_custom_image_1' => ['label' => 'Eigenes Bild für Beitrag 1 (URL)', 'type' => 'text', 'default' => ''],
                'sidebar_featured_custom_image_2' => ['label' => 'Eigenes Bild für Beitrag 2 (URL)', 'type' => 'text', 'default' => ''],
                'sidebar_featured_custom_image_3' => ['label' => 'Eigenes Bild für Beitrag 3 (URL)', 'type' => 'text', 'default' => ''],
                'sidebar_featured_custom_image_4' => ['label' => 'Eigenes Bild für Beitrag 4 (URL)', 'type' => 'text', 'default' => ''],
                'sidebar_featured_custom_image_5' => ['label' => 'Eigenes Bild für Beitrag 5 (URL)', 'type' => 'text', 'default' => ''],
                'sidebar_featured_custom_image_6' => ['label' => 'Eigenes Bild für Beitrag 6 (URL)', 'type' => 'text', 'default' => ''],
                'show_info_grid'             => ['label' => 'Kategorie-Cards anzeigen',     'type' => 'checkbox', 'default' => true],
                'info_card1_title'           => ['label' => 'Info-Card 1 Titel',            'type' => 'text',     'default' => '🖥️ Admin Anleitungen'],
                'info_card1_text'            => ['label' => 'Info-Card 1 Text',             'type' => 'textarea', 'default' => 'Schritt-für-Schritt-Tutorials für Microsoft 365 Administration.'],
                'info_card1_link_text'       => ['label' => 'Info-Card 1 Link-Text',        'type' => 'text',     'default' => 'Alle Anleitungen ansehen →'],
                'info_card1_link_url'        => ['label' => 'Info-Card 1 Link URL',         'type' => 'text',     'default' => '/kategorie/anleitungen'],
                'info_card1_style'           => ['label' => 'Info-Card 1 Stil',             'type' => 'select',   'default' => 'default', 'options' => ['default' => 'Standard (Blau)', 'gold' => 'Gold-Akzent']],
                'info_card2_title'           => ['label' => 'Info-Card 2 Titel',            'type' => 'text',     'default' => '🔒 DSGVO & Compliance'],
                'info_card2_text'            => ['label' => 'Info-Card 2 Text',             'type' => 'textarea', 'default' => 'Konfigurationsanleitungen und Best Practices für Microsoft Purview.'],
                'info_card2_link_text'       => ['label' => 'Info-Card 2 Link-Text',        'type' => 'text',     'default' => 'Compliance-Center →'],
                'info_card2_link_url'        => ['label' => 'Info-Card 2 Link URL',         'type' => 'text',     'default' => '/kategorie/compliance'],
                'info_card2_style'           => ['label' => 'Info-Card 2 Stil',             'type' => 'select',   'default' => 'gold',    'options' => ['default' => 'Standard (Blau)', 'gold' => 'Gold-Akzent']],
                'show_info_card3'            => ['label' => 'Info-Card 3 anzeigen',         'type' => 'checkbox', 'default' => false],
                'info_card3_title'           => ['label' => 'Info-Card 3 Titel',            'type' => 'text',     'default' => 'Open Source'],
                'info_card3_text'            => ['label' => 'Info-Card 3 Text',             'type' => 'text',     'default' => 'Meine Projekte auf GitHub.'],
                'info_card3_link_text'       => ['label' => 'Info-Card 3 Link-Text',        'type' => 'text',     'default' => 'Zum Repository →'],
                'info_card3_link_url'        => ['label' => 'Info-Card 3 Link URL',         'type' => 'text',     'default' => 'https://github.com/'],
                'info_card3_badge'           => ['label' => 'Info-Card 3 Badge',            'type' => 'text',     'default' => 'GitHub'],
                'info_card3_style'           => ['label' => 'Info-Card 3 Stil',             'type' => 'select',   'default' => 'repo',    'options' => ['default' => 'Standard (Blau)', 'gold' => 'Gold-Akzent', 'repo' => 'Repo (Dark)']],
                'show_tile_grid'             => ['label' => 'Deep-Dive Grid anzeigen',      'type' => 'checkbox', 'default' => true],
                'tile_grid_label'            => ['label' => 'Grid Sektion-Label',           'type' => 'text',     'default' => 'Deep-Dive Archiv'],
                'tile_grid_count'            => ['label' => 'Anzahl Kacheln',               'type' => 'number',   'default' => '6'],
                'tile_grid_columns'          => ['label' => 'Grid-Spalten',                 'type' => 'select',   'default' => '3', 'options' => ['2' => '2 Spalten', '3' => '3 Spalten (Standard)', '4' => '4 Spalten']],
                'show_tile_excerpt'          => ['label' => 'Grid: Auszug anzeigen',        'type' => 'checkbox', 'default' => true],
                'show_tile_category'         => ['label' => 'Grid: Kategorie-Badge',        'type' => 'checkbox', 'default' => true],
                'show_tile_date'             => ['label' => 'Grid: Datum anzeigen',         'type' => 'checkbox', 'default' => true],
                'tile_grid_image_height'     => ['label' => 'Kartenbildhöhe im Grid (px)',  'type' => 'number',   'default' => '161', 'min' => 161, 'max' => 300],
                'tile_grid_link_url'         => ['label' => '„Archiv" URL',                'type' => 'text',     'default' => '/archiv'],
                'show_feed_section'          => ['label' => 'RSS-Feed-Sektion anzeigen',    'type' => 'checkbox', 'default' => false],
                'feed1_channel_id'           => ['label' => 'Feed 1 – Kanal (cms-feed)',    'type' => 'select',   'default' => '0', 'options' => ['0' => '— Kein Feed —']],
                'feed1_count'                => ['label' => 'Feed 1 – Anzahl Einträge',     'type' => 'number',   'default' => '5'],
                'feed2_channel_id'           => ['label' => 'Feed 2 – Kanal (cms-feed)',    'type' => 'select',   'default' => '0', 'options' => ['0' => '— Kein Feed —']],
                'feed2_count'                => ['label' => 'Feed 2 – Anzahl Einträge',     'type' => 'number',   'default' => '5'],
                'spacing_repo_card'          => ['label' => 'Abstand nach Repo-Card (px)',  'type' => 'number',   'default' => '32'],
                'spacing_article_list'       => ['label' => 'Abstand nach Artikel-Liste (px)','type' => 'number', 'default' => '32'],
                'spacing_info_cards'         => ['label' => 'Abstand nach Kategorie-Cards (px)', 'type' => 'number', 'default' => '32'],
                'spacing_tile_grid'          => ['label' => 'Abstand nach Kachel-Grid (px)','type' => 'number',   'default' => '32'],
                'spacing_rss_feeds'          => ['label' => 'Abstand nach RSS-Feeds (px)',  'type' => 'number',   'default' => '0'],
                'home_header_content_spacing'=> ['label' => 'Abstand Header → erste Startseiten-Sektion / Repo-Card (px)', 'type' => 'number', 'default' => '15', 'min' => 0, 'max' => 30],
            ],
        ],
        'posts' => [
            'title' => '📝 Beiträge',
            'sections' => [
                'post_hero_height'       => ['label' => 'Beitragsbild Höhe (px)',           'type' => 'number',   'default' => '215'],
                'post_hero_width'        => ['label' => 'Beitragsbild Breite (px)',         'type' => 'number',   'default' => '162'],
                'show_post_hero'         => ['label' => 'Beitragsbild links vom Titel',     'type' => 'checkbox', 'default' => true],
                'post_title_fontsize'    => ['label' => 'Beitrags-Titel Schriftgröße (px)', 'type' => 'number',   'default' => '28'],
                'show_post_meta'         => ['label' => 'Artikel-Meta anzeigen',            'type' => 'checkbox', 'default' => true],
                'show_reading_time'      => ['label' => 'Lesezeit anzeigen',                'type' => 'checkbox', 'default' => true],
                'reading_time_wpm'       => ['label' => 'Wörter pro Minute',                'type' => 'number',   'default' => '220'],
                'show_toc'               => ['label' => 'Inhaltsverzeichnis anzeigen',      'type' => 'checkbox', 'default' => true],
                'toc_sticky'             => ['label' => 'TOC sticky',                       'type' => 'checkbox', 'default' => true],
                'toc_min_headings'       => ['label' => 'TOC ab mind. X Überschriften',     'type' => 'number',   'default' => '2'],
                'toc_header_text'        => ['label' => 'TOC Widget-Titel',                 'type' => 'text',     'default' => 'Inhaltsverzeichnis'],
                'show_sidebar_social'    => ['label' => 'Social-Widget in Sidebar',         'type' => 'checkbox', 'default' => true],
                'sidebar_social_header'  => ['label' => 'Social-Widget Titel',              'type' => 'text',     'default' => 'Folgen & Teilen'],
                'show_sidebar_related'   => ['label' => 'Verwandte Artikel in Sidebar',     'type' => 'checkbox', 'default' => true],
                'sidebar_related_header' => ['label' => 'Verwandte Artikel Titel',          'type' => 'text',     'default' => 'Verwandte Artikel'],
                'related_count'          => ['label' => 'Anzahl verwandter Artikel',        'type' => 'number',   'default' => '4'],
                'show_share_buttons'     => ['label' => 'Share-Buttons anzeigen',           'type' => 'checkbox', 'default' => true],
                'show_share_linkedin'    => ['label' => 'LinkedIn Share',                   'type' => 'checkbox', 'default' => true],
                'show_share_twitter'     => ['label' => 'Twitter/X Share',                  'type' => 'checkbox', 'default' => true],
                'show_share_email'       => ['label' => 'E-Mail Share',                     'type' => 'checkbox', 'default' => true],
                'show_share_copy'        => ['label' => 'Link kopieren',                    'type' => 'checkbox', 'default' => true],
                'show_tech_card'         => ['label' => 'Tech-Infocard (post-tech)',        'type' => 'checkbox', 'default' => true],
                'tech_card_header'       => ['label' => 'Tech-Card Titel',                  'type' => 'text',     'default' => 'Tech-Details'],
                'show_comments'          => ['label' => 'Kommentarbereich anzeigen',        'type' => 'checkbox', 'default' => true],
                'comments_header'        => ['label' => 'Kommentare Titel',                 'type' => 'text',     'default' => 'Kommentare'],
                'comment_form_header'    => ['label' => 'Kommentarformular Titel',          'type' => 'text',     'default' => 'Kommentar hinterlassen'],
                'show_post_tags'         => ['label' => 'Tags anzeigen',                    'type' => 'checkbox', 'default' => true],
            ],
        ],
        'pages' => [
            'title' => '📄 Seiten',
            'sections' => [
                'show_page_title'        => ['label' => 'Seiten-Titel anzeigen',           'type' => 'checkbox', 'default' => true],
                'page_title_fontsize'    => ['label' => 'Seiten-Titel Schriftgröße (px)',  'type' => 'number',   'default' => '28'],
                'show_page_hero'         => ['label' => 'Seiten-Bild links vom Titel',     'type' => 'checkbox', 'default' => true],
                'show_page_updated_date' => ['label' => 'Aktualisierungsdatum',            'type' => 'checkbox', 'default' => false],
                'page_layout'            => ['label' => 'Seiten-Layout',                   'type' => 'select',   'default' => 'full', 'options' => ['full' => 'Volle Breite', 'narrow' => 'Schmal (860 px)', 'two-col' => 'Zweispaltig']],
                'show_page_sidebar'      => ['label' => 'Sidebar auf Seiten',              'type' => 'checkbox', 'default' => false],
                'page_sidebar_show_nav'  => ['label' => 'Sidebar: Navigations-Widget',     'type' => 'checkbox', 'default' => true],
                'show_page_toc'          => ['label' => 'Inhaltsverzeichnis auf Seiten',   'type' => 'checkbox', 'default' => false],
            ],
        ],
        'social' => [
            'title' => '🌐 Social Media',
            'sections' => [
                'social_linkedin'       => ['label' => 'LinkedIn URL',          'type' => 'text', 'default' => ''],
                'social_github'         => ['label' => 'GitHub URL',            'type' => 'text', 'default' => ''],
                'social_gitlab'         => ['label' => 'GitLab URL',            'type' => 'text', 'default' => ''],
                'social_twitter'        => ['label' => 'Twitter/X URL',         'type' => 'text', 'default' => ''],
                'social_mastodon'       => ['label' => 'Mastodon URL',          'type' => 'text', 'default' => ''],
                'social_rss'            => ['label' => 'RSS-Feed URL',          'type' => 'text', 'default' => '/feed'],
                'social_youtube'        => ['label' => 'YouTube URL',           'type' => 'text', 'default' => ''],
                'social_xing'           => ['label' => 'Xing URL',              'type' => 'text', 'default' => ''],
                'social_label_linkedin' => ['label' => 'LinkedIn Button-Label', 'type' => 'text', 'default' => 'LinkedIn'],
                'social_label_github'   => ['label' => 'GitHub Button-Label',   'type' => 'text', 'default' => 'GitHub'],
                'social_label_gitlab'   => ['label' => 'GitLab Button-Label',   'type' => 'text', 'default' => 'GitLab'],
                'social_label_rss'      => ['label' => 'RSS Button-Label',      'type' => 'text', 'default' => 'RSS Feed'],
            ],
        ],
        'advanced' => [
            'title' => '🔧 Erweitert',
            'sections' => [
                'custom_css'          => ['label' => 'Eigenes CSS',              'type' => 'textarea', 'default' => ''],
                'custom_head_code'    => ['label' => 'Custom Head Code',         'type' => 'textarea', 'default' => ''],
                'custom_footer_code'  => ['label' => 'Custom Footer Code',       'type' => 'textarea', 'default' => ''],
                'google_analytics_id' => ['label' => 'Google Analytics ID',      'type' => 'text',     'default' => ''],
                'cache_buster_css'    => ['label' => 'CSS Cache-Buster Version', 'type' => 'text',     'default' => ''],
                'og_default_image'    => ['label' => 'Standard OG-Bild URL (Fallback für Social-Sharing)', 'type' => 'text', 'default' => ''],
            ],
        ],
        'seo' => [
            'title' => '🔍 SEO',
            'sections' => [
                'meta_robots'       => ['label' => 'Meta Robots (Standard)',       'type' => 'select',   'default' => 'index,follow', 'options' => ['index,follow' => 'index, follow', 'noindex,follow' => 'noindex, follow', 'noindex,nofollow' => 'noindex, nofollow']],
                'canonical_self'    => ['label' => 'Canonical-Tag auf eigene URL', 'type' => 'checkbox', 'default' => true],
                'og_site_name'      => ['label' => 'OG Site Name',                 'type' => 'text',     'default' => ''],
                'og_type_default'   => ['label' => 'OG Type (Standard)',           'type' => 'select',   'default' => 'website', 'options' => ['website' => 'website', 'blog' => 'blog', 'article' => 'article']],
                'twitter_card_type' => ['label' => 'Twitter Card Type',            'type' => 'select',   'default' => 'summary_large_image', 'options' => ['summary_large_image' => 'summary_large_image', 'summary' => 'summary']],
                'structured_data'   => ['label' => 'Schema.org Markup aktiv',      'type' => 'checkbox', 'default' => true],
                'breadcrumb_schema' => ['label' => 'Breadcrumb Schema aktiv',      'type' => 'checkbox', 'default' => true],
                'noindex_search'    => ['label' => 'Suchseite noindex',            'type' => 'checkbox', 'default' => true],
                'noindex_404'       => ['label' => '404-Seite noindex',            'type' => 'checkbox', 'default' => true],
            ],
        ],
        'performance' => [
            'title' => '⚡ Performance',
            'sections' => [
                'enable_photoswipe' => ['label' => 'PhotoSwipe Lightbox aktiv',                  'type' => 'checkbox', 'default' => true],
                'lazyload_images'   => ['label' => 'Bilder Lazy-Load (loading=lazy)',            'type' => 'checkbox', 'default' => true],
                'preconnect_fonts'  => ['label' => 'Preconnect Google Fonts',                    'type' => 'checkbox', 'default' => true],
                'preconnect_extra'  => ['label' => 'Zusätzliche Preconnect-URLs (eine pro Zeile)', 'type' => 'textarea', 'default' => ''],
                'defer_scripts'     => ['label' => 'Theme-Scripts defer',                        'type' => 'checkbox', 'default' => true],
                'dns_prefetch'      => ['label' => 'DNS-Prefetch aktiv',                         'type' => 'checkbox', 'default' => true],
            ],
        ],
    ],
    'tabGroups' => [
        'colors'     => ['🎨 Markenfarben' => ['primary_color','primary_dark','primary_mid','primary_light','accent_color','accent_hover'], '💻 Tech-Akzente' => ['accent_blue','accent_blue2','accent_teal','accent_teal_light'], '🖼️ Header-BGs' => ['bg_header1','bg_header2','bg_header3'], '📄 Seite & Dark' => ['bg_primary','bg_secondary','bg_dark','page_edge_tint_color'], '📝 Textfarben' => ['text_primary','text_secondary','text_muted'], '🧭 Navigation' => ['text_nav','text_nav_member','text_nav_main','text_nav_quicklinks','text_nav_dropdown','logo_suffix_color'], '🔲 Rahmen & Footer' => ['border_light','footer_bg','footer_bottom_bg','footer_border'], '✅ Status & Progress' => ['success_color','error_color','progress_bar_start','progress_bar_end']],
        'typography' => ['🔤 Schriftarten' => ['font_family_ui','font_family_brand','font_family_code'], '📏 Größen & Abstände' => ['font_size_base','font_size_post','line_height_base','line_height_post','font_weight_heading','font_weight_nav'], '📝 Card-Texte' => ['article_title_fontsize','tile_title_fontsize','article_excerpt_fontsize','article_excerpt_length','tile_excerpt_fontsize','tile_excerpt_length']],
        'layout'     => ['📐 Maße' => ['container_width','page_edge_tint_opacity','sidebar_width','border_radius','border_radius_md','content_gap','spacing_header_content','spacing_content_footer','spacing_sections'], '🍞 Breadcrumb' => ['show_breadcrumb','breadcrumb_on_posts','breadcrumb_on_pages'], '⚙️ Funktionen' => ['sidebar_position','enable_sticky_header','enable_progress_bar','enable_back_to_top','enable_dark_mode_toggle','enable_scroll_animations']],
        'header'     => ['🏷️ Logo & Marke' => ['logo_text_part1','logo_text_part2','logo_text_suffix','logo_url','show_logo_text_with_image','logo_max_height','logo_accent_color'], '👤 Member-Bar' => ['show_member_bar','member_bar_height'], '🧭 Hauptnav' => ['main_nav_height','show_search_bar','search_placeholder','show_rss_link'], '⚡ Quicklinks' => ['show_quicklinks','sub_bar_height'], '🌍 Sprache' => ['show_language_switcher','language_switcher_mode','language_switcher_label','language_switcher_slug','language_switcher_flag','language_switcher_aria_label']],
        'footer'     => ['🏷️ Brand & Text' => ['footer_brand_name','footer_tagline','footer_col2_title','footer_col3_title','footer_col4_title','copyright_text','show_footer_social'], '🍪 Cookie-Consent' => ['show_consent_banner','consent_text','consent_privacy_url'], '🔗 Network-Bar' => ['show_network_bar','network_bar_link1_label','network_bar_link1_url','network_bar_link2_label','network_bar_link2_url','network_bar_link3_label','network_bar_link3_url','network_bar_link4_label','network_bar_link4_url','network_bar_link5_label','network_bar_link5_url']],
        'homepage'   => ['📌 Repo-Card' => ['show_repo_card','repo_card_title','repo_card_description','repo_card_badge','repo_card_btn_text','repo_card_btn_url'], '📰 Artikel-Liste' => ['show_article_list','article_list_label','article_list_count','article_list_link_url','article_thumb_width','article_thumb_height','show_article_excerpt','show_article_meta','show_article_badge','show_meta_category','show_meta_date','show_meta_readtime'], '🗂️ Kategorie-Cards' => ['show_info_grid','info_card1_title','info_card1_text','info_card1_link_text','info_card1_link_url','info_card1_style','info_card2_title','info_card2_text','info_card2_link_text','info_card2_link_url','info_card2_style','show_info_card3','info_card3_title','info_card3_text','info_card3_link_text','info_card3_link_url','info_card3_badge','info_card3_style'], '🧱 Kachel-Grid & Bildhöhe' => ['show_tile_grid','tile_grid_label','tile_grid_count','tile_grid_columns','show_tile_excerpt','show_tile_category','show_tile_date','tile_grid_image_height','tile_grid_link_url'], '📡 RSS-Feeds' => ['show_feed_section','feed1_channel_id','feed1_count','feed2_channel_id','feed2_count'], '📏 Sektionen-Abstände' => ['home_header_content_spacing','spacing_repo_card','spacing_article_list','spacing_info_cards','spacing_tile_grid','spacing_rss_feeds']],
        'posts'      => ['🖼️ Hero & Meta' => ['post_hero_height','post_hero_width','show_post_hero','post_title_fontsize','show_post_meta','show_reading_time','reading_time_wpm'], '📖 Inhaltsverzeichnis' => ['show_toc','toc_sticky','toc_min_headings','toc_header_text'], '📌 Sidebar-Widgets' => ['show_sidebar_social','sidebar_social_header','show_sidebar_related','sidebar_related_header','related_count'], '🔗 Share-Buttons' => ['show_share_buttons','show_share_linkedin','show_share_twitter','show_share_email','show_share_copy'], '💻 Tech-Card' => ['show_tech_card','tech_card_header'], '💬 Kommentare & Tags' => ['show_comments','comments_header','comment_form_header','show_post_tags']],
        'pages'      => ['📄 Seiteneinstellungen' => ['show_page_title','page_title_fontsize','show_page_hero','show_page_updated_date','page_layout','show_page_sidebar','page_sidebar_show_nav','show_page_toc']],
        'social'     => ['🔗 Profile & URLs' => ['social_linkedin','social_github','social_gitlab','social_twitter','social_mastodon','social_rss','social_youtube','social_xing'], '🏷️ Button-Labels' => ['social_label_linkedin','social_label_github','social_label_gitlab','social_label_rss']],
        'advanced'   => ['🎨 Custom Code' => ['custom_css','custom_head_code','custom_footer_code'], '📊 Tracking & Cache' => ['google_analytics_id','cache_buster_css'], '🖼️ SEO & Social' => ['og_default_image']],
        'seo'        => ['🔍 SEO-Einstellungen' => ['meta_robots','canonical_self','og_site_name','og_type_default','twitter_card_type','structured_data','breadcrumb_schema','noindex_search','noindex_404']],
        'performance'=> ['⚡ Performance-Einstellungen' => ['enable_photoswipe','lazyload_images','preconnect_fonts','preconnect_extra','defer_scripts','dns_prefetch']],
        'memberdashboard' => ['📣 Admin-Hinweis' => ['show_admin_notice','admin_notice_roles','admin_notice_variant','admin_notice_accent_color','admin_notice_background_color','admin_notice_kicker','admin_notice_title','admin_notice_text','admin_notice_link_label','admin_notice_link_url'], '👋 Begrüßung' => ['show_welcome','welcome_eyebrow','welcome_title','welcome_text','hero_panel_title'], '🧭 Sidebar-Menü' => ['show_sidebar_dashboard','show_sidebar_profile','show_sidebar_notifications','show_sidebar_favorites','show_sidebar_comments','show_sidebar_newsletter','show_sidebar_feeds','show_sidebar_forum','show_sidebar_security','show_sidebar_analytics','show_sidebar_admin_link','sidebar_admin_label','sidebar_admin_icon'], '🎛️ Hero-Aktionen' => ['show_hero_favorites','show_hero_profile','show_hero_security','show_hero_notifications','show_hero_comments','show_hero_analytics'], '🧩 Info-Cards' => ['show_card_favorites','show_card_comments','show_card_notifications','show_card_posts','show_card_security','overview_card_order','card_favorites_title','card_favorites_icon','card_comments_title','card_comments_icon','card_notifications_title','card_notifications_icon','card_posts_title','card_posts_icon','card_security_title','card_security_icon'], '📚 Dashboard-Blöcke' => ['show_recent_comments','show_recent_favorites','show_recent_notifications','recent_comments_title','recent_comments_icon','recent_favorites_title','recent_favorites_icon','recent_notifications_title','recent_notifications_icon','show_quicklinks','quicklinks_title','quicklinks_icon'], '🎨 Farben' => ['sidebar_active_color','hero_color_start','hero_color_end','card_icon_color','card_hover_color','quicklink_icon_color'], '⚡ Schnellzugriff' => ['show_quicklink_profile','show_quicklink_notifications','show_quicklink_newsletter','show_quicklink_feeds','show_quicklink_forum']],
    ],
    'tabViews' => [
        'homepage-sidebar' => [
            'title' => '🏠 Startseiten-Sidebar',
            'fields' => [
                ['tab' => 'homepage', 'key' => 'show_list_sidebar'],
                ['tab' => 'homepage', 'key' => 'list_sidebar_width'],
                ['tab' => 'homepage', 'key' => 'list_sidebar_title'],
                ['tab' => 'homepage', 'key' => 'list_sidebar_content'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_identity'],
                ['tab' => 'homepage', 'key' => 'sidebar_identity_logo_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_identity_tagline'],
                ['tab' => 'homepage', 'key' => 'sidebar_identity_link_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_projects'],
                ['tab' => 'homepage', 'key' => 'sidebar_project1_name'],
                ['tab' => 'homepage', 'key' => 'sidebar_project1_logo_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_project1_desc'],
                ['tab' => 'homepage', 'key' => 'sidebar_project1_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_project2_name'],
                ['tab' => 'homepage', 'key' => 'sidebar_project2_logo_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_project2_desc'],
                ['tab' => 'homepage', 'key' => 'sidebar_project2_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_status'],
                ['tab' => 'homepage', 'key' => 'sidebar_status_label'],
                ['tab' => 'homepage', 'key' => 'sidebar_status_services'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_downloads'],
                ['tab' => 'homepage', 'key' => 'sidebar_downloads_label'],
                ['tab' => 'homepage', 'key' => 'sidebar_downloads_items'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_social'],
                ['tab' => 'homepage', 'key' => 'sidebar_social_label'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_notice'],
                ['tab' => 'homepage', 'key' => 'sidebar_notice_title'],
                ['tab' => 'homepage', 'key' => 'sidebar_notice_text'],
                ['tab' => 'homepage', 'key' => 'sidebar_notice_url'],
                ['tab' => 'homepage', 'key' => 'sidebar_notice_url_text'],
                ['tab' => 'homepage', 'key' => 'sidebar_show_featured_posts'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_posts_label'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_badge_style'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_rotate_seconds'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_title_size'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_badge_size'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_image_layout'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_post_1'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_post_2'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_post_3'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_post_4'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_post_5'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_post_6'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_custom_image_1'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_custom_image_2'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_custom_image_3'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_custom_image_4'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_custom_image_5'],
                ['tab' => 'homepage', 'key' => 'sidebar_featured_custom_image_6'],
            ],
            'groups' => [
                '📋 Sidebar neben Liste' => ['show_list_sidebar','list_sidebar_width','list_sidebar_title','list_sidebar_content'],
                '🪪 Site-Identity' => ['sidebar_show_identity','sidebar_identity_logo_url','sidebar_identity_tagline','sidebar_identity_link_url'],
                '🚀 Projekte' => ['sidebar_show_projects','sidebar_project1_name','sidebar_project1_logo_url','sidebar_project1_desc','sidebar_project1_url','sidebar_project2_name','sidebar_project2_logo_url','sidebar_project2_desc','sidebar_project2_url'],
                '🟢 Status & Downloads' => ['sidebar_show_status','sidebar_status_label','sidebar_status_services','sidebar_show_downloads','sidebar_downloads_label','sidebar_downloads_items'],
                '📣 Social, Hinweis & Featured' => ['sidebar_show_social','sidebar_social_label','sidebar_show_notice','sidebar_notice_title','sidebar_notice_text','sidebar_notice_url','sidebar_notice_url_text','sidebar_show_featured_posts','sidebar_featured_posts_label','sidebar_featured_badge_style','sidebar_featured_rotate_seconds','sidebar_featured_title_size','sidebar_featured_badge_size','sidebar_featured_image_layout','sidebar_featured_post_1','sidebar_featured_custom_image_1','sidebar_featured_post_2','sidebar_featured_custom_image_2','sidebar_featured_post_3','sidebar_featured_custom_image_3','sidebar_featured_post_4','sidebar_featured_custom_image_4','sidebar_featured_post_5','sidebar_featured_custom_image_5','sidebar_featured_post_6','sidebar_featured_custom_image_6'],
            ],
        ],
        'posts-sidebar' => [
            'title' => '📝 Beitrags-Sidebar',
            'fields' => [
                ['tab' => 'layout', 'key' => 'sidebar_width'],
                ['tab' => 'layout', 'key' => 'sidebar_position'],
                ['tab' => 'posts', 'key' => 'show_toc'],
                ['tab' => 'posts', 'key' => 'toc_sticky'],
                ['tab' => 'posts', 'key' => 'toc_min_headings'],
                ['tab' => 'posts', 'key' => 'toc_header_text'],
                ['tab' => 'posts', 'key' => 'show_sidebar_social'],
                ['tab' => 'posts', 'key' => 'sidebar_social_header'],
                ['tab' => 'posts', 'key' => 'show_sidebar_related'],
                ['tab' => 'posts', 'key' => 'sidebar_related_header'],
                ['tab' => 'posts', 'key' => 'related_count'],
            ],
            'groups' => [
                '📐 Layout & Position' => ['sidebar_width','sidebar_position'],
                '📖 Inhaltsverzeichnis' => ['show_toc','toc_sticky','toc_min_headings','toc_header_text'],
                '🔗 Sidebar-Widgets' => ['show_sidebar_social','sidebar_social_header','show_sidebar_related','sidebar_related_header','related_count'],
            ],
        ],
    ],
    'navGroups' => [
        null        => ['colors', 'typography', 'layout'],
        '🖥️ Design' => ['header', 'footer'],
        '📝 Inhalte' => ['homepage', 'homepage-sidebar', 'posts', 'posts-sidebar', 'pages', 'memberdashboard'],
        '⚙️ Sonstiges' => ['social', 'advanced', 'seo', 'performance'],
    ],
];
